
import type { Vehicle } from './types';

export const VEHICLES_0KM: Vehicle[] = [
  {
    id: 6,
    make: 'BYD',
    model: 'DOLPHIN MINI GS',
    year: 2025,
    price: 23990,
    kms: 0,
    fuel: 'Eléctrico',
    transmission: 'Automática',
    image: '/images/0km/byd-dolphin.jpg',
    type: '0km',
    description: 'Vehículo eléctrico compacto color verde. También disponible en versión GL.',
    priceCurrency: 'USD',
  },
  {
    id: 7,
    make: 'BYD',
    model: 'YUAN PRO GS',
    year: 2025,
    price: 30990,
    kms: 0,
    fuel: 'Eléctrico',
    transmission: 'Automática',
    image: '/images/0km/byd-yuan.jpg',
    type: '0km',
    description: 'SUV eléctrico color gris oscuro. También disponible en versión GL.',
    priceCurrency: 'USD',
  },
  {
    id: 8,
    make: 'BYD',
    model: 'SONG PRO GS',
    year: 2025,
    price: 36990,
    kms: 0,
    fuel: 'Eléctrico',
    transmission: 'Automática',
    image: '/images/0km/byd-song.jpg',
    type: '0km',
    description: 'SUV eléctrico en colores celeste y gris. También disponible en versión GL.',
    priceCurrency: 'USD',
  },
  {
    id: 10,
    make: 'CORADIR',
    model: 'TITO S2 300',
    year: 2025,
    price: 16723,
    kms: 0,
    fuel: 'Eléctrico',
    transmission: 'Automática',
    image: '/images/0km/coradir-tito-s2.jpg',
    type: '0km',
    description: 'Vehículo eléctrico 3 puertas con aire acondicionado, autonomía 300 km, color rojo.',
    priceCurrency: 'USD',
  },
  {
    id: 11,
    make: 'CORADIR',
    model: 'TITO S5',
    year: 2025,
    price: 17732,
    kms: 0,
    fuel: 'Eléctrico',
    transmission: 'Automática',
    image: '/images/0km/coradir-tito-s5.jpg',
    type: '0km',
    description: 'Vehículo eléctrico 5 puertas con autonomía 300 km, color blanco.',
    priceCurrency: 'USD',
  },
  {
    id: 12,
    make: 'CORADIR',
    model: 'TITA PICK-UP ELECTRICA',
    year: 2025,
    price: 17800,
    kms: 0,
    fuel: 'Eléctrico',
    transmission: 'Automática',
    image: '/images/0km/coradir-tita-pickup.jpg',
    type: '0km',
    description: 'Pick-up eléctrica con autonomía 300 km, color blanco.',
    priceCurrency: 'USD',
  },
  {
    id: 13,
    make: 'CORADIR',
    model: 'TITA PICK-UP FURGÓN REFRIGERADO',
    year: 2025,
    price: 23632,
    kms: 0,
    fuel: 'Eléctrico',
    transmission: 'Automática',
    image: '/images/0km/coradir-tita-furgon.jpg',
    type: '0km',
    description: 'Pick-up eléctrica furgón refrigerado, autonomía 300 km, color blanco.',
    priceCurrency: 'USD',
  },
  {
    id: 14,
    make: 'CORADIR',
    model: 'TITA CUADRILLA DOBLE CABINA',
    year: 2025,
    price: 18732,
    kms: 0,
    fuel: 'Eléctrico',
    transmission: 'Automática',
    image: '/images/0km/coradir-tita-cuadrilla.jpg',
    type: '0km',
    description: 'Pick-up eléctrica doble cabina 4 puertas con aire acondicionado, autonomía 300 km, color blanco.',
    priceCurrency: 'USD',
  },
  {
    id: 15,
    make: 'CITROEN',
    model: 'C3 VTI AT6 FEEL PACK MY24',
    year: 2025,
    price: 26900000,
    kms: 0,
    fuel: 'Nafta',
    transmission: 'Automática',
    image: '/images/0km/citroen-c3.jpg',
    type: '0km',
    description: 'Hatchback compacto con transmisión automática AT6, color blanco.',
  },
  {
    id: 16,
    make: 'CITROEN',
    model: 'C3 VTI AT6 FEEL PACK MY24 BITONO',
    year: 2025,
    price: 27900000,
    kms: 0,
    fuel: 'Nafta',
    transmission: 'Automática',
    image: '/images/0km/citroen-c3-bitono.jpg',
    type: '0km',
    description: 'Hatchbook compacto con transmisión automática AT6, versión bitono azul con techo blanco.',
  },
  {
    id: 18,
    make: 'CITROEN',
    model: 'BERLINGO FURGÓN HDI 92 HP BUSINESS',
    year: 2025,
    price: 28900000,
    kms: 0,
    fuel: 'Nafta',
    transmission: 'Manual',
    image: '/images/0km/citroen-berlingo.jpg',
    type: '0km',
    description: 'Furgón comercial HDI 92 HP versión Business, color blanco.',
  },
  {
    id: 19,
    make: 'CHEVROLET',
    model: 'TRACKER PREMIER 1.2L AT',
    year: 2020,
    price: 26900000,
    kms: 0,
    fuel: 'Nafta',
    transmission: 'Automática',
    image: '/images/0km/chevrolet-tracker.jpg',
    type: '0km',
    description: 'SUV compacta Premier 1.2L con transmisión automática, color bordeaux.',
  },
  {
    id: 20,
    make: 'CHEVROLET',
    model: 'SPIN 1.8 N LT MT',
    year: 2025,
    price: 31500000,
    kms: 0,
    fuel: 'Nafta',
    transmission: 'Manual',
    image: '/images/0km/chevrolet-spin.jpg',
    type: '0km',
    description: 'Monovolumen familiar 1.8L LT con transmisión manual, color gris plata.',
  },
  {
    id: 21,
    make: 'CHRYSLER',
    model: 'JEEP COMPASS BLACKHAWK 1.3L TURBO AT6 4X2',
    year: 2025,
    price: 62900000,
    kms: 0,
    fuel: 'Nafta',
    transmission: 'Automática',
    image: '/images/0km/jeep-compass.jpg',
    type: '0km',
    description: 'SUV Compass Blackhawk 1.3L Turbo con transmisión automática AT6 4X2, color negro perla.',
  },
  {
    id: 22,
    make: 'CHRYSLER',
    model: 'RAM 1500 LARAMIE NIGHT EDITION 4X4 AT',
    year: 2025,
    price: 53900000,
    kms: 0,
    fuel: 'Nafta',
    transmission: 'Automática',
    image: '/images/0km/ram-1500.jpg',
    type: '0km',
    description: 'Pick-up Ram 1500 Laramie Night Edition 4X4 con transmisión automática, color Sting Grey.',
  },
  {
    id: 23,
    make: 'CHRYSLER',
    model: 'RAM RAMPAGE RT',
    year: 2025,
    price: 64900000,
    kms: 0,
    fuel: 'Nafta',
    transmission: 'Automática',
    image: '/images/0km/ram-rampage.jpg',
    type: '0km',
    description: 'Pick-up Ram Rampage RT de alto rendimiento, color negro perla.',
  },
  {
    id: 26,
    make: 'CHRYSLER',
    model: 'JEEP RENEGADE SPORT 1.3L TURBO AT6',
    year: 2025,
    price: 35900000,
    kms: 0,
    fuel: 'Nafta',
    transmission: 'Automática',
    image: '/images/0km/jeep-renegade-sport.jpg',
    type: '0km',
    description: 'SUV compacta Renegade Sport 1.3L Turbo con transmisión automática AT6, bitono blanco y negro.',
  },
  {
    id: 29,
    make: 'FIAT',
    model: 'FASTBACK TURBO 270 AT MY24',
    year: 2025,
    price: 37900000,
    kms: 0,
    fuel: 'Nafta',
    transmission: 'Automática',
    image: '/images/0km/fiat-fastback.jpg',
    type: '0km',
    description: 'SUV coupé Fastback Turbo 270 con transmisión automática, color rojo Montecarlo.',
  },
  {
    id: 30,
    make: 'FIAT',
    model: 'CRONOS LIKE GSE 1.3 16V MT',
    year: 2022,
    price: 26900000,
    kms: 0,
    fuel: 'Nafta',
    transmission: 'Manual',
    image: '/images/0km/cronos.jpg',
    type: '0km',
    description: 'Sedán Cronos Like GSE 1.3 16V con transmisión manual, color rojo. Código AF126TS.',
  },
  {
    id: 31,
    make: 'FIAT',
    model: 'CRONOS DRIVE GSE 1.3 16V MT',
    year: 2025,
    price: 28900000,
    kms: 0,
    fuel: 'Nafta',
    transmission: 'Manual',
    image: '/images/0km/fiat-cronos-drive.jpg',
    type: '0km',
    description: 'Sedán Cronos Drive GSE 1.3 16V con transmisión manual, color blanco perlado.',
  },
  {
    id: 32,
    make: 'FIAT',
    model: 'CRONOS DRIVE GSE 1.3 16V AUTOMATICO',
    year: 2025,
    price: 29900000,
    kms: 0,
    fuel: 'Nafta',
    transmission: 'Automática',
    image: '/images/0km/fiat-cronos-auto.jpg',
    type: '0km',
    description: 'Sedán Cronos Drive GSE 1.3 16V con transmisión automática, color gris Silverstone.',
  },
  {
    id: 34,
    make: 'FIAT',
    model: 'STRADA ULTRA T200 D/C 1.3L CVT',
    year: 2025,
    price: 36900000,
    kms: 0,
    fuel: 'Nafta',
    transmission: 'Automática',
    image: '/images/0km/fiat-strada.jpg',
    type: '0km',
    description: 'Pick-up Strada Ultra T200 doble cabina 1.3L con transmisión CVT, colores rojo y blanco.',
  },
  {
    id: 36,
    make: 'FIAT',
    model: 'STRADA FREEDOM 1.3 8V MT C/DOBLE',
    year: 2025,
    price: 27900000,
    kms: 0,
    fuel: 'Nafta',
    transmission: 'Manual',
    image: '/images/0km/fiat-strada-freedom.jpg',
    type: '0km',
    description: 'Pick-up Strada Freedom 1.3 8V cabina doble con transmisión manual, color negro Plata Bari.',
  },
  {
    id: 37,
    make: 'FORD',
    model: 'NUEVA MAVERICK LARIAT HIBRIDA AWD',
    year: 2025,
    price: 57900000,
    kms: 0,
    fuel: 'Híbrido',
    transmission: 'Automática',
    image: '/images/0km/ford-maverick.jpg',
    type: '0km',
    description: 'Pick-up Maverick Lariat híbrida con tracción AWD, color blanco.',
  },
  {
    id: 38,
    make: 'FORD',
    model: 'NUEVA RANGER 2.0L TURBO XL 4X4 MT',
    year: 2025,
    price: 51900000,
    kms: 0,
    fuel: 'Nafta',
    transmission: 'Manual',
    image: '/images/0km/ford-ranger-xl.jpg',
    type: '0km',
    description: 'Pick-up Ranger 2.0L Turbo XL 4X4 con transmisión manual, color azul Belice.',
  },
  {
    id: 39,
    make: 'FORD',
    model: 'NUEVA RANGER 2.0L TURBO XLS 4X2 MT',
    year: 2025,
    price: 49900000,
    kms: 0,
    fuel: 'Nafta',
    transmission: 'Manual',
    image: '/images/0km/ford-ranger-xls.jpg',
    type: '0km',
    description: 'Pick-up Ranger 2.0L Turbo XLS 4X2 con transmisión manual, color blanco.',
  },
  {
    id: 40,
    make: 'FORD',
    model: 'NUEVA RANGER XLT 2.0L BI-TURBO 4X2 AT10 MY 25.5',
    year: 2025,
    price: 57900000,
    kms: 0,
    fuel: 'Nafta',
    transmission: 'Automática',
    image: '/images/0km/ford-ranger-xlt.jpg',
    type: '0km',
    description: 'Pick-up Ranger XLT 2.0L Bi-Turbo 4X2 con transmisión automática AT10 MY25.5, color azul Belice.',
  },
  {
    id: 41,
    make: 'FORD',
    model: 'NUEVA RANGER XLT 2.0 BI-TURBO 4X4 AT10',
    year: 2025,
    price: 62900000,
    kms: 0,
    fuel: 'Nafta',
    transmission: 'Automática',
    image: '/images/0km/ford-ranger-xlt-4x4.jpg',
    type: '0km',
    description: 'Pick-up Ranger XLT 2.0 Bi-Turbo 4X4 con transmisión automática AT10, color naranja Terra.',
  },
  {
    id: 42,
    make: 'FORD',
    model: 'NUEVA RANGER LIMITED 2.0 210CV 4X4 AT MY25,5',
    year: 2025,
    price: 67900000,
    kms: 0,
    fuel: 'Nafta',
    transmission: 'Automática',
    image: '/images/0km/ford-ranger-limited.jpg',
    type: '0km',
    description: 'Pick-up Ranger Limited 2.0 210CV 4X4 con transmisión automática MY25.5, color plata metalizado.',
  },
  {
    id: 43,
    make: 'FORD',
    model: 'NUEVA RANGER LIMITED+ PLUS 3.0 V6 250HP 4X4 AT10',
    year: 2025,
    price: 75900000,
    kms: 0,
    fuel: 'Nafta',
    transmission: 'Automática',
    image: '/images/0km/ford-ranger-limited-plus.jpg',
    type: '0km',
    description: 'Pick-up Ranger Limited+ Plus 3.0 V6 250HP 4X4 con transmisión automática AT10, color negro perlado.',
  },
  {
    id: 44,
    make: 'FORD',
    model: 'NUEVA RANGER 3.0 V6 XLS 250CV 4WD AT',
    year: 2025,
    price: 61900000,
    kms: 0,
    fuel: 'Nafta',
    transmission: 'Automática',
    image: '/images/0km/ford-ranger-v6-xls.jpg',
    type: '0km',
    description: 'Pick-up Ranger 3.0 V6 XLS 250CV 4WD con transmisión automática, color naranja.',
  },
  {
    id: 45,
    make: 'FORD',
    model: 'NUEVA RANGER BLACK 2.0L 4X4 MT6 170CV',
    year: 2025,
    price: 59900000,
    kms: 0,
    fuel: 'Nafta',
    transmission: 'Manual',
    image: '/images/0km/ford-ranger-black.jpg',
    type: '0km',
    description: 'Pick-up Ranger Black 2.0L 4X4 170CV con transmisión manual MT6, bitono negro y gris plata.',
  },
  {
    id: 46,
    make: 'FORD',
    model: 'TERRITORY SEL 1.5T 143HP CVT',
    year: 2025,
    price: 46900000,
    kms: 0,
    fuel: 'Nafta',
    transmission: 'Automática',
    image: '/images/0km/ford-territory-sel.jpg',
    type: '0km',
    description: 'SUV Territory SEL 1.5T 143HP con transmisión CVT, color gris oscuro.',
  },
  {
    id: 47,
    make: 'FORD',
    model: 'TERRITORY TITANIUM 1.5T 143HP CVT',
    year: 2025,
    price: 56900000,
    kms: 0,
    fuel: 'Nafta',
    transmission: 'Automática',
    image: '/images/0km/ford-territory-titanium.jpg',
    type: '0km',
    description: 'SUV Territory Titanium 1.5T 143HP con transmisión CVT, color blanco perlado.',
  },
  {
    id: 48,
    make: 'FORD',
    model: 'BRONCO 2.0 SPORT WILDTRACK 4X4 AT6',
    year: 2025,
    price: 59900000,
    kms: 0,
    fuel: 'Nafta',
    transmission: 'Automática',
    image: '/images/0km/ford-bronco.jpg',
    type: '0km',
    description: 'SUV Bronco 2.0 Sport Wildtrack 4X4 con transmisión automática AT6, color blanco Oxford.',
  },
  {
    id: 49,
    make: 'FORD',
    model: 'NUEVA MAVERICK XLT 4X2 AT',
    year: 2025,
    price: 40900000,
    kms: 0,
    fuel: 'Nafta',
    transmission: 'Automática',
    image: '/images/0km/ford-maverick-xlt.jpg',
    type: '0km',
    description: 'Pick-up Maverick XLT 4X2 con transmisión automática, disponible en varios colores.',
  },
  {
    id: 50,
    make: 'FORD',
    model: 'TRANSIT MINIBUS AT',
    year: 2025,
    price: 73900000,
    kms: 0,
    fuel: 'Nafta',
    transmission: 'Automática',
    image: '/images/0km/ford-transit-minibus.jpg',
    type: '0km',
    description: 'Minibus Transit con transmisión automática, color blanco.',
  },
  {
    id: 51,
    make: 'FORD',
    model: 'TRANSIT CHASIS MT',
    year: 2025,
    price: 46900000,
    kms: 0,
    fuel: 'Nafta',
    transmission: 'Manual',
    image: '/images/0km/ford-transit-chasis.jpg',
    type: '0km',
    description: 'Chasis Transit con transmisión manual, color blanco.',
  },
  {
    id: 52,
    make: 'FOTON',
    model: 'TM1 CABINA SIMPLE 1.5L 110HP',
    year: 2025,
    price: 26500,
    kms: 0,
    fuel: 'Nafta',
    transmission: 'Manual',
    image: '/images/0km/foton-tm1-simple.jpg',
    type: '0km',
    description: 'Pick-up TM1 cabina simple 1.5L 110HP con capacidad de carga 1630 kg, color blanco.',
    priceCurrency: 'USD',
  },
  {
    id: 53,
    make: 'FOTON',
    model: 'TM1 CABINA DOBLE 1.5L 110HP',
    year: 2025,
    price: 29900,
    kms: 0,
    fuel: 'Nafta',
    transmission: 'Manual',
    image: '/images/0km/foton-tm1-doble.jpg',
    type: '0km',
    description: 'Pick-up TM1 cabina doble 1.5L 110HP con capacidad de carga 1580 kg, color blanco.',
    priceCurrency: 'USD',
  },
  {
    id: 54,
    make: 'FOTON',
    model: 'TM1 CABINA SIMPLE 1.5L 110HP BOX CARGO',
    year: 2025,
    price: 31700,
    kms: 0,
    fuel: 'Nafta',
    transmission: 'Manual',
    image: '/images/0km/foton-tm1-box.jpg',
    type: '0km',
    description: 'Pick-up TM1 cabina simple 1.5L 110HP con box cargo, capacidad 1300 kg, color blanco.',
    priceCurrency: 'USD',
  },
  {
    id: 55,
    make: 'FOTON',
    model: 'TM1 CAB. SP. 1.5L 110HP BOX CARGO REFRIGERADO',
    year: 2025,
    price: 39900,
    kms: 0,
    fuel: 'Nafta',
    transmission: 'Manual',
    image: '/images/0km/foton-tm1-refrigerado.jpg',
    type: '0km',
    description: 'Pick-up TM1 cabina simple 1.5L 110HP con box cargo refrigerado, color blanco.',
    priceCurrency: 'USD',
  },
  {
    id: 56,
    make: 'FOTON',
    model: 'TM2 CAB. SIMPLE C/DUALES',
    year: 2025,
    price: 29500,
    kms: 0,
    fuel: 'Nafta',
    transmission: 'Manual',
    image: '/images/0km/foton-tm2.jpg',
    type: '0km',
    description: 'Pick-up TM2 cabina simple con ruedas duales, capacidad de carga 2200 kg, color blanco.',
    priceCurrency: 'USD',
  },
  {
    id: 57,
    make: 'HONDA',
    model: 'NEW HR-V 2WD 1.6L 121HP CVT L/N 2026',
    year: 2025,
    price: 46290000,
    kms: 0,
    fuel: 'Nafta',
    transmission: 'Automática',
    image: '/images/0km/honda-hrv.jpg',
    type: '0km',
    description: 'SUV HR-V 2WD 1.6L 121HP con transmisión CVT línea nueva 2026, color gris plata.',
  },
  {
    id: 58,
    make: 'HONDA',
    model: 'NEW HR-V EXL 2WD 1.6L 121HP CVT L/N 2026',
    year: 2025,
    price: 52900000,
    kms: 0,
    fuel: 'Nafta',
    transmission: 'Automática',
    image: '/images/0km/honda-hrv-exl.jpg',
    type: '0km',
    description: 'SUV HR-V EXL 2WD 1.6L 121HP con transmisión CVT línea nueva 2026, colores azul y blanco perla.',
  },
  {
    id: 59,
    make: 'JEEP',
    model: 'RENEGADE LONGITUDE 1.3 T270 LINEA NUEVA',
    year: 2025,
    price: 43900000,
    kms: 0,
    fuel: 'Nafta',
    transmission: 'Automática',
    image: '/images/0km/renegade.jpg',
    type: '0km',
    description: 'SUV Renegade Longitude 1.3 T270 línea nueva, color gris oscuro.',
  },
  {
    id: 60,
    make: 'JEEP',
    model: 'COMMANDER 4X2 T270 1.3L',
    year: 2025,
    price: 55900000,
    kms: 0,
    fuel: 'Nafta',
    transmission: 'Automática',
    image: '/images/0km/jeep-commander.jpg',
    type: '0km',
    description: 'SUV Commander 4X2 T270 1.3L, color gris plata.',
  },
  {
    id: 69,
    make: 'MITSUBISHI',
    model: 'L200 LINEA NUEVA 4X4 AT',
    year: 2025,
    price: 53900000,
    kms: 0,
    fuel: 'Nafta',
    transmission: 'Automática',
    image: '/images/0km/mitsubishi-l200.jpg',
    type: '0km',
    description: 'Pick-up L200 línea nueva 4X4 con transmisión automática, colores azul y blanco perla.',
  },
  {
    id: 70,
    make: 'NISSAN',
    model: 'VERSA EXCLUSIVE CVT 1.6 118HP',
    year: 2025,
    price: 39900000,
    kms: 0,
    fuel: 'Nafta',
    transmission: 'Automática',
    image: '/images/0km/nissan-versa.jpg',
    type: '0km',
    description: 'Sedán Versa Exclusive CVT 1.6 118HP, color bordó.',
  },
  {
    id: 71,
    make: 'NISSAN',
    model: 'KICKS ADVANCE CVT PLUS',
    year: 2025,
    price: 42500000,
    kms: 0,
    fuel: 'Nafta',
    transmission: 'Automática',
    image: '/images/0km/nissan-kicks.jpg',
    type: '0km',
    description: 'SUV Kicks Advance CVT Plus, color blanco.',
  },
  {
    id: 72,
    make: 'NISSAN',
    model: 'FRONTIER S 4X2 MT',
    year: 2025,
    price: 43900000,
    kms: 0,
    fuel: 'Nafta',
    transmission: 'Manual',
    image: '/images/0km/nissan-frontier.jpg',
    type: '0km',
    description: 'Pick-up Frontier S 4X2 con transmisión manual, color blanco.',
  },
  {
    id: 74,
    make: 'PEUGEOT',
    model: '208 ALLURE PACK 1.0L AT MY26',
    year: 2025,
    price: 32900000,
    kms: 0,
    fuel: 'Nafta',
    transmission: 'Automática',
    image: '/images/0km/peugeot-208.jpg',
    type: '0km',
    description: 'Hatchback 208 Allure Pack 1.0L con transmisión automática MY26, color azul Quasar.',
  },
  {
    id: 75,
    make: 'PEUGEOT',
    model: 'PARTNER CONFORT FURGON 1.6 HDI 115HP',
    year: 2025,
    price: 31500000,
    kms: 0,
    fuel: 'Diesel',
    transmission: 'Manual',
    image: '/images/0km/peugeot-partner.jpg',
    type: '0km',
    description: 'Furgón Partner Confort 1.6 HDI 115HP, color blanco.',
  },
  {
    id: 76,
    make: 'PEUGEOT',
    model: '3008 GT PACK THP NAFTA CVT',
    year: 2025,
    price: 72900000,
    kms: 0,
    fuel: 'Nafta',
    transmission: 'Automática',
    image: '/images/0km/peugeot-3008.jpg',
    type: '0km',
    description: 'SUV 3008 GT Pack THP con transmisión CVT, color gris Artense.',
  },
  {
    id: 77,
    make: 'PEUGEOT',
    model: '2008 GT 200 CVT 7V MY24',
    year: 2025,
    price: 39900000,
    kms: 0,
    fuel: 'Nafta',
    transmission: 'Automática',
    image: '/images/0km/peugeot-2008.jpg',
    type: '0km',
    description: 'SUV 2008 GT 200 CVT 7V MY24, color blanco perlado.',
  },
  {
    id: 78,
    make: 'PEUGEOT',
    model: 'NUEVO 408 1.6L + HYBRID AT',
    year: 2025,
    price: 73900000,
    kms: 0,
    fuel: 'Híbrido',
    transmission: 'Automática',
    image: '/images/0km/peugeot-408.jpg',
    type: '0km',
    description: 'Sedán 408 1.6L + Hybrid con transmisión automática, color blanco perlado.',
  },
  {
    id: 79,
    make: 'PEUGEOT',
    model: 'EXPERT 2.2L HDI 150HP 6 PAX AT',
    year: 2025,
    price: 57900000,
    kms: 0,
    fuel: 'Diesel',
    transmission: 'Automática',
    image: '/images/0km/peugeot-expert.jpg',
    type: '0km',
    description: 'Furgón Expert 2.2L HDI 150HP para 6 pasajeros con transmisión automática, color gris plata.',
  },
  {
    id: 80,
    make: 'RENAULT',
    model: 'LOGAN 1.6L 16V LIFE',
    year: 2025,
    price: 25900000,
    kms: 0,
    fuel: 'Nafta',
    transmission: 'Manual',
    image: '/images/0km/renault-logan.jpg',
    type: '0km',
    description: 'Sedán Logan 1.6L 16V Life, color gris estrella.',
  },
  {
    id: 81,
    make: 'RENAULT',
    model: 'ARKANA 1,3 TCE E-TECH HYBRID ESPIRIT ALPINE',
    year: 2025,
    price: 43900000,
    kms: 0,
    fuel: 'Híbrido',
    transmission: 'Automática',
    image: '/images/0km/renault-arkana.jpg',
    type: '0km',
    description: 'SUV coupé Arkana 1.3 TCE E-Tech Hybrid Espirit Alpine, color negro.',
  },
  {
    id: 82,
    make: 'RENAULT',
    model: 'KARDIAN 1.0T EVOLUTION EDC. L25',
    year: 2025,
    price: 33900000,
    kms: 0,
    fuel: 'Nafta',
    transmission: 'Automática',
    image: '/images/0km/renault-kardian.jpg',
    type: '0km',
    description: 'SUV Kardian 1.0T Evolution EDC L25, color gris plata.',
  },
  {
    id: 85,
    make: 'RENAULT',
    model: 'KOLEOS 1.5T E-TECH HYBRID ESPIRIT ALPINE AT',
    year: 2025,
    price: 83900000,
    kms: 0,
    fuel: 'Híbrido',
    transmission: 'Automática',
    image: '/images/0km/renault-koleos.jpg',
    type: '0km',
    description: 'SUV Koleos 1.5T E-Tech Hybrid Espirit Alpine con transmisión automática, color blanco Oxford.',
  },
  {
    id: 86,
    make: 'RENAULT',
    model: 'KWID 1.0L ICONIC BT L24',
    year: 2025,
    price: 19900000,
    kms: 0,
    fuel: 'Nafta',
    transmission: 'Manual',
    image: '/images/0km/mini-1743771826003.KWID-ICONIC-01.jpg',
    type: '0km',
    description: 'SUV urbana Kwid 1.0L Iconic BT L24, color naranja.',
  },
  {
    id: 88,
    make: 'TOYOTA',
    model: 'HIACE L2H2 2.8 TDI AT6',
    year: 2025,
    price: 59900000,
    kms: 0,
    fuel: 'Diesel',
    transmission: 'Automática',
    image: '/images/0km/toyota-hiace.jpg',
    type: '0km',
    description: 'Furgón Hiace L2H2 2.8 TDI con transmisión automática AT6, color blanco perlado.',
  },
  {
    id: 89,
    make: 'TOYOTA',
    model: 'HILUX SR 2.8L 4X4 AUT',
    year: 2025,
    price: 61900000,
    kms: 0,
    fuel: 'Diesel',
    transmission: 'Automática',
    image: '/images/0km/toyota-hilux-sr.jpg',
    type: '0km',
    description: 'Pick-up Hilux SR 2.8L 4X4 con transmisión automática, color gris plata.',
  },
  {
    id: 90,
    make: 'TOYOTA',
    model: 'HILUX SRX 2.8L 4X4 AUT LINEA NUEVA',
    year: 2025,
    price: 73900000,
    kms: 0,
    fuel: 'Diesel',
    transmission: 'Automática',
    image: '/images/0km/toyota-hilux-srx.jpg',
    type: '0km',
    description: 'Pick-up Hilux SRX 2.8L 4X4 línea nueva con transmisión automática, colores gris plata y gris oscuro.',
  },
  {
    id: 91,
    make: 'TOYOTA',
    model: 'COROLLA SEDAN XEI 1.8 HIBRIDO CVT',
    year: 2025,
    price: 44900000,
    kms: 0,
    fuel: 'Híbrido',
    transmission: 'Automática',
    image: '/images/0km/toyota-corolla-hybrid.jpg',
    type: '0km',
    description: 'Sedán Corolla XEI 1.8 híbrido con transmisión CVT, color blanco perlado.',
  },
  {
    id: 92,
    make: 'TOYOTA',
    model: 'COROLLA XEI SEDAN MT6 2.0L',
    year: 2025,
    price: 45900000,
    kms: 0,
    fuel: 'Nafta',
    transmission: 'Manual',
    image: '/images/0km/toyota-corolla-xei.jpg',
    type: '0km',
    description: 'Sedán Corolla XEI 2.0L con transmisión manual MT6, color blanco puro.',
  },
  {
    id: 93,
    make: 'TOYOTA',
    model: 'COROLLA SEDAN GRS AT10V 2.0L',
    year: 2025,
    price: 53900000,
    kms: 0,
    fuel: 'Nafta',
    transmission: 'Automática',
    image: '/images/0km/toyota-corolla-grs.jpg',
    type: '0km',
    description: 'Sedán Corolla GRS AT10V 2.0L, bitono blanco con techo negro.',
  },
  {
    id: 95,
    make: 'TOYOTA',
    model: 'YARIS "S" 5 PTS. 1.5L CVT',
    year: 2025,
    price: 36900000,
    kms: 0,
    fuel: 'Nafta',
    transmission: 'Automática',
    image: '/images/0km/toyota-yaris.jpg',
    type: '0km',
    description: 'Hatchback Yaris "S" 5 puertas 1.5L con transmisión CVT, colores blanco perlado y rojo.',
  },
  {
    id: 96,
    make: 'TOYOTA',
    model: 'SW4 DIAMOND LINEA 2025',
    year: 2025,
    price: 93900000,
    kms: 0,
    fuel: 'Nafta',
    transmission: 'Automática',
    image: '/images/0km/toyota-sw4-diamond.jpg',
    type: '0km',
    description: 'SUV SW4 Diamond línea 2025, colores negro y gris oscuro.',
  },
  {
    id: 97,
    make: 'TOYOTA',
    model: 'SW4 GR-S MY25',
    year: 2025,
    price: 93900000,
    kms: 0,
    fuel: 'Nafta',
    transmission: 'Automática',
    image: '/images/0km/toyota-sw4-grs.jpg',
    type: '0km',
    description: 'SUV SW4 GR-S MY25 versión deportiva, color negra.',
  },
  {
    id: 98,
    make: 'TOYOTA',
    model: 'SW4 SRX 2.8 TDI AT6 7 ASIENTOS',
    year: 2025,
    price: 79900000,
    kms: 0,
    fuel: 'Diesel',
    transmission: 'Automática',
    image: '/images/0km/toyota-sw4-srx.jpg',
    type: '0km',
    description: 'SUV SW4 SRX 2.8 TDI AT6 para 7 asientos, colores blanco y gris plata.',
  },
  {
    id: 99,
    make: 'TOYOTA',
    model: 'HILUX DX 2.4 TDI 6MT 4X2',
    year: 2025,
    price: 43900000,
    kms: 0,
    fuel: 'Diesel',
    transmission: 'Manual',
    image: '/images/0km/toyota-hilux-dx.jpg',
    type: '0km',
    description: 'Pick-up Hilux DX 2.4 TDI 6MT 4X2, color blanco.',
  },
  {
    id: 100,
    make: 'TOYOTA',
    model: 'HILUX SRV PLUS AT 2.8 TDI',
    year: 2025,
    price: 69900000,
    kms: 0,
    fuel: 'Diesel',
    transmission: 'Automática',
    image: '/images/0km/toyota-hilux-srv.jpg',
    type: '0km',
    description: 'Pick-up Hilux SRV Plus AT 2.8 TDI, color gris oscuro.',
  },
  {
    id: 101,
    make: 'VOLKSWAGEN',
    model: 'TIGUAN R-LINE 250 TSI DSG7 150CV',
    year: 2025,
    price: 77900000,
    kms: 0,
    fuel: 'Nafta',
    transmission: 'Automática',
    image: '/images/0km/vw-tiguan.jpg',
    type: '0km',
    description: 'SUV Tiguan R-Line 250 TSI DSG7 150CV, color azul Pacífico.',
  },
  {
    id: 102,
    make: 'VOLKSWAGEN',
    model: 'VENTO GLI 2.0 TSI 230CV MT',
    year: 2025,
    price: 65900000,
    kms: 0,
    fuel: 'Nafta',
    transmission: 'Manual',
    image: '/images/0km/vw-vento-gli.jpg',
    type: '0km',
    description: 'Sedán deportivo Vento GLI 2.0 TSI 230CV con transmisión manual, color gris platino.',
  },
  {
    id: 103,
    make: 'VOLKSWAGEN',
    model: 'AMAROK V6 HIGHLINE 3.0 G2 4X4 AT8',
    year: 2025,
    price: 66900000,
    kms: 0,
    fuel: 'Nafta',
    transmission: 'Automática',
    image: '/images/0km/vw-amarok-v6.jpg',
    type: '0km',
    description: 'Pick-up Amarok V6 Highline 3.0 G2 4X4 con transmisión automática AT8, color plata Pirita.',
  },
  {
    id: 104,
    make: 'VOLKSWAGEN',
    model: 'AMAROK TRENDLINE 4X2 MT6 2.0L TDI',
    year: 2025,
    price: 44900000,
    kms: 0,
    fuel: 'Diesel',
    transmission: 'Manual',
    image: '/images/0km/vw-amarok-trendline.jpg',
    type: '0km',
    description: 'Pick-up Amarok Trendline 4X2 MT6 2.0L TDI, color blanca.',
  },
  {
    id: 105,
    make: 'VOLKSWAGEN',
    model: 'AMAROK HIGHLINE 2.0 D/C 4X2 AT',
    year: 2025,
    price: 59900000,
    kms: 0,
    fuel: 'Diesel',
    transmission: 'Automática',
    image: '/images/0km/vw-amarok-highline.jpg',
    type: '0km',
    description: 'Pick-up Amarok Highline 2.0 doble cabina 4X2 con transmisión automática, color champagne.',
  },
  {
    id: 106,
    make: 'VOLKSWAGEN',
    model: 'TAOS CONFORTLINE CVT MY25',
    year: 2025,
    price: 45900000,
    kms: 0,
    fuel: 'Nafta',
    transmission: 'Automática',
    image: '/images/0km/vw-taos-confortline.jpg',
    type: '0km',
    description: 'SUV Taos Confortline CVT MY25, color blanco perlado.',
  },
  {
    id: 107,
    make: 'VOLKSWAGEN',
    model: 'TAOS HIGHLINE AT6 1.4L',
    year: 2025,
    price: 49900000,
    kms: 0,
    fuel: 'Nafta',
    transmission: 'Automática',
    image: '/images/0km/vw-taos-highline.jpg',
    type: '0km',
    description: 'SUV Taos Highline AT6 1.4L, color gris Indy.',
  },
  {
    id: 108,
    make: 'VOLKSWAGEN',
    model: 'TERA CONFORTLINE 170TSI AUT',
    year: 2025,
    price: 36900000,
    kms: 0,
    fuel: 'Nafta',
    transmission: 'Automática',
    image: '/images/0km/vw-tera-confortline.jpg',
    type: '0km',
    description: 'Sedán Tera Confortline 170TSI con transmisión automática, color gris platino.',
  },
  {
    id: 109,
    make: 'VOLKSWAGEN',
    model: 'TERA TRENDLINE MT',
    year: 2025,
    price: 31500000,
    kms: 0,
    fuel: 'Nafta',
    transmission: 'Manual',
    image: '/images/0km/vw-tera-trendline.jpg',
    type: '0km',
    description: 'Sedán Tera Trendline con transmisión manual, color blanco.',
  },
  {
    id: 110,
    make: 'ZANELLA',
    model: 'Z-TRUCK PICK-UP CABINA DOBLE',
    year: 2025,
    price: 24900,
    kms: 0,
    fuel: 'Nafta',
    transmission: 'Manual',
    image: '/images/0km/zanella-z-truck-doble.jpg',
    type: '0km',
    description: 'Pick-up Z-Truck cabina doble, color blanco.',
    priceCurrency: 'USD',
  },
  {
    id: 111,
    make: 'ZANELLA',
    model: 'Z-TRUCK PICK-UP CABINA SIMPLE 85HP',
    year: 2025,
    price: 22900,
    kms: 0,
    fuel: 'Nafta',
    transmission: 'Manual',
    image: '/images/0km/zanella-z-truck-simple.jpg',
    type: '0km',
    description: 'Pick-up Z-Truck cabina simple 85HP con capacidad de carga 1200 kg, color blanco.',
    priceCurrency: 'USD',
  },
];

export const VEHICLES_USED: Vehicle[] = [
  {
    id: 1,
    make: 'Peugeot',
    model: '208 Feline Tiptronic 1.6L',
    year: 2023,
    price: 25900000,
    kms: 57000,
    fuel: 'Nafta',
    transmission: 'Automática',
    image: '/images/used-cars/208.1.png',
    type: 'usado',
    description: 'Sedán 5 puertas con caja automática, 57.000 km, color blanco perlado, línea nueva pantalla grande.',
  },
  {
    id: 2,
    make: 'Fiat',
    model: 'Toro Freedom 1.8L Nafta/GNC',
    year: 2019,
    price: 24900000,
    kms: 79000,
    fuel: 'Nafta/GNC',
    transmission: 'Automática',
    image: '/images/used-cars/toro1.png',
    type: 'usado',
    description: '4x2 AT6 con accesorios, cubiertas nuevas, tubo 16 metros 3", único dueño, color blanco.',
  },
  {
    id: 3,
    make: 'Citroën',
    model: 'DS3 Puretech 110 AT6 SO CHIC',
    year: 2018,
    price: 17900000,
    kms: 73000,
    fuel: 'Nafta',
    transmission: 'Automática',
    image: '/images/used-cars/ds3.1.png',
    type: 'usado',
    description: 'Sedán 3 puertas, color blanco perlado, único dueño, impecable estado.',
  },
  {
    id: 4,
    make: 'Mercedes-Benz',
    model: 'A200 Urban',
    year: 2017,
    price: 26500,
    kms: 42747,
    fuel: 'Nafta',
    transmission: 'Automática',
    image: '/images/used-cars/a200.1.png',
    type: 'usado',
    description: 'Sedán 5 puertas, caja automática, único dueño, impecable, color gris claro.',
    priceCurrency: 'USD',
  },
  {
    id: 5,
    make: 'Citroën',
    model: 'C3',
    year: 2021,
    price: 18500000,
    kms: 38000,
    fuel: 'Nafta',
    transmission: 'Manual',
    image: '/images/used-cars/c3.1.png',
    type: 'usado',
    description: 'Hatchback compacto con diseño moderno y eficiencia de combustible.',
  },
  {
    id: 7,
    make: 'Fiat',
    model: 'Cronos',
    year: 2022,
    price: 19500000,
    kms: 35000,
    fuel: 'Nafta',
    transmission: 'Manual',
    image: '/images/used-cars/cronos1.png',
    type: 'usado',
    description: 'Sedán compacto con diseño italiano y tecnología moderna.',
  },
  {
    id: 9,
    make: 'Kia',
    model: 'Sportage EX 2.0 A/T 4X4 CRDI',
    year: 2019,
    price: 45900000,
    kms: 30000,
    fuel: 'Diesel',
    transmission: 'Automática',
    image: '/images/used-cars/kia1.png',
    type: 'usado',
    description: 'Todo terreno diesel, impecable, nuevo, único dueño sin detalles, color gris.',
  },
  {
    id: 10,
    make: 'Renault',
    model: 'Laguna',
    year: 2019,
    price: 23500000,
    kms: 65000,
    fuel: 'Nafta',
    transmission: 'Automática',
    image: '/images/used-cars/laguna1.png',
    type: 'usado',
    description: 'Sedán mediano con confort y tecnología francesa.',
  },
  {
    id: 11,
    make: 'Suzuki',
    model: 'Maruti Gypsy GLS',
    year: 1994,
    price: 19900000,
    kms: 89000,
    fuel: 'Nafta',
    transmission: 'Manual',
    image: '/images/used-cars/maruti1.png',
    type: 'usado',
    description: 'Motor 1.0L 4X4, canvas top, caja manual, único en el país, digno de ver, todo 0 km, impecable 100%, color rojo.',
  },
  {
    id: 12,
    make: 'Audi',
    model: 'Q5 2.0 TFSI 211CV S-Tronic Quattro',
    year: 2013,
    price: 25900000,
    kms: 130000,
    fuel: 'Nafta',
    transmission: 'Automática',
    image: '/images/used-cars/q5.1.png',
    type: 'usado',
    description: 'Único dueño, 130.000 kmts, exterior blanco, color gris plata.',
  },
  {
    id: 15,
    make: 'BMW',
    model: '530D Executive 3.0L',
    year: 2024,
    price: 18500000,
    kms: 0,
    fuel: 'Diesel',
    transmission: 'Automática Steptronic 6ª',
    image: '/images/used-cars/Bmw530D/a4b657_194ae5adf64c4d1a9b755fc192b64037mv2.png',
    type: 'usado',
    description: 'Caja Steptronic Automática 6ª Secuencial, 4 Puertas Diesel',
  },
  {
    id: 16,
    make: 'Mercedes Benz',
    model: '380 SEC Coupe',
    year: 1990,
    price: 24900,
    kms: 95808,
    fuel: 'Nafta',
    transmission: 'Automática',
    image: '/images/used-cars/MB-380SEC/a4b657_5261d850c20e4fb6b021bdb81494f029mv2.png',
    type: 'usado',
    description: 'Único dueño! En impecable estado. Auto de colección.',
    priceCurrency: 'USD',
  },
  {
    id: 17,
    make: 'Mercedes Benz',
    model: 'Sportcoupe C230 V6 Evolution',
    year: 2006,
    price: 16900,
    kms: 0,
    fuel: 'Nafta',
    transmission: 'Automática',
    image: '/images/used-cars/MB-C230/a4b657_00020d7485a947d69ae72abb72603bdamv2.png',
    type: 'usado',
    description: 'Impecable estado. V6 Evolution Automático 2006.',
    priceCurrency: 'USD',
  },
];
