
import type { Vehicle } from './types';

export const VEHICLES_0KM: Vehicle[] = [
  {
    id: 1,
    make: 'Renault',
    model: 'Kwid Outsider 1.0',
    year: 2025,
    price: 18500000,
    kms: 0,
    fuel: 'Nafta',
    transmission: 'Manual',
    image: '/images/0km/mini-1743707561761.KWID-OUTSIDER-01.jpg',
    type: '0km',
    description: 'SUV compacta con diseño aventurero y tecnología moderna.',
  },
  {
    id: 2,
    make: 'Renault',
    model: 'Kwid Iconic 1.0',
    year: 2025,
    price: 17500000,
    kms: 0,
    fuel: 'Nafta',
    transmission: 'Manual',
    image: '/images/0km/mini-1743771826003.KWID-ICONIC-01.jpg',
    type: '0km',
    description: 'Versión icónica con equipamiento completo y confort premium.',
  },
  {
    id: 3,
    make: 'Fiat',
    model: 'Cronos 1.3',
    year: 2025,
    price: 22500000,
    kms: 0,
    fuel: 'Nafta',
    transmission: 'Manual',
    image: '/images/0km/mini-1747337165053.nuevo-fiat-cronos-15.jpg',
    type: '0km',
    description: 'Sedán compacto familiar con motor 1.3L 8 válvulas de 99 CV y 127 Nm. Fabricado en Argentina, incluye nueva parrilla Pixel, luces LED DRL, multimedia de 7" con Apple CarPlay y Android Auto inalámbrico, y 4 airbags.',
  },
  {
    id: 4,
    make: 'Renault',
    model: 'Stepway 1.6',
    year: 2025,
    price: 28500000,
    kms: 0,
    fuel: 'Nafta',
    transmission: 'Manual',
    image: '/images/0km/mini-1624984882569.1.jpg',
    type: '0km',
    description: 'Crossover urbano con motor HR16 1.6L, 115 CV, altura al suelo 185mm y baúl de 320 litros. Incluye cuatro airbags, control crucero, faros LED C-Shape y llantas de aleación 16".',
  },
  {
    id: 5,
    make: 'Renault',
    model: 'Logan Life 1.6',
    year: 2025,
    price: 24500000,
    kms: 0,
    fuel: 'Nafta',
    transmission: 'Manual',
    image: '/images/0km/mini-1667835477981.1.jpg',
    type: '0km',
    description: 'Sedán familiar con motor H4M 1.6L de 115 CV y 156 Nm. Versión básica con comando satelital, cierre centralizado, sistema de audio básico y equipamiento de seguridad reglamentario.',
  },
  {
    id: 6,
    make: 'Renault',
    model: 'Logan Intens 1.6',
    year: 2025,
    price: 27500000,
    kms: 0,
    fuel: 'Nafta',
    transmission: 'Manual',
    image: '/images/0km/mini-1673013426019.1.jpg',
    type: '0km',
    description: 'Sedán familiar con motor H4M 1.6L de 115 CV. Versión superior con Media Evolution® 7", Android Auto y Apple CarPlay, cámara de reversa, sensores de estacionamiento, ESP, HSA, faros DRL LED y mayor confort.',
  },
  {
    id: 7,
    make: 'Volkswagen',
    model: 'Polo Track',
    year: 2025,
    price: 27500000,
    kms: 0,
    fuel: 'Nafta',
    transmission: 'Manual',
    image: '/images/0km/mini-1691441178832.1.jpg',
    type: '0km',
    description: 'Hatchback compacto con motor 3 cilindros, torque de 170Nm, velocidad máxima 183km/h y aceleración 0-100 en 11.5s. Incluye ESC, ABS, 4 airbags, App Connect inalámbrico, cargador inalámbrico y sistema VW Play con Android Auto y Apple CarPlay.',
  },
  {
    id: 8,
    make: 'Renault',
    model: 'Sandero',
    year: 2025,
    price: 19500000,
    kms: 0,
    fuel: 'Nafta',
    transmission: 'Manual',
    image: '/images/0km/mini-1694204505047.1.jpg',
    type: '0km',
    description: 'Hatchback urbano con motor 1.6L 16 válvulas, baúl de 320 litros y capacidad para 5 pasajeros. Incluye cámara de estacionamiento trasera, control crucero, sistema Media Evolution® con pantalla de 7" y llantas de aleación 15".',
  },
  {
    id: 9,
    make: 'Fiat',
    model: 'Fiorino 1.3',
    year: 2025,
    price: 18500000,
    kms: 0,
    fuel: 'Nafta',
    transmission: 'Manual',
    image: '/images/0km/mini-1709563961450.1.jpg',
    type: '0km',
    description: 'Furgón utilitario pequeño con motor Firefly 1.3L de 99 CV y 130 Nm. Capacidad de carga 3.3m³ y 650kg. Incluye aire acondicionado, cierre centralizado, doble airbag, ABS, ESP, sensores de estacionamiento y alarma.',
  },
];

export const VEHICLES_USED: Vehicle[] = [
  {
    id: 1,
    make: 'Peugeot',
    model: '208 Feline Tiptronic 1.6L',
    year: 2023,
    price: 25900000,
    kms: 57000,
    fuel: 'Nafta',
    transmission: 'Automática',
    image: '/images/used-cars/208.1.png',
    type: 'usado',
    description: 'Sedán 5 puertas con caja automática, 57.000 km, color blanco perlado, línea nueva pantalla grande.',
  },
  {
    id: 2,
    make: 'Fiat',
    model: 'Toro Freedom 1.8L Nafta/GNC',
    year: 2019,
    price: 24900000,
    kms: 79000,
    fuel: 'Nafta/GNC',
    transmission: 'Automática',
    image: '/images/used-cars/toro1.png',
    type: 'usado',
    description: '4x2 AT6 con accesorios, cubiertas nuevas, tubo 16 metros 3", único dueño, color blanco.',
  },
  {
    id: 3,
    make: 'Citroën',
    model: 'DS3 Puretech 110 AT6 SO CHIC',
    year: 2018,
    price: 17900000,
    kms: 73000,
    fuel: 'Nafta',
    transmission: 'Automática',
    image: '/images/used-cars/ds3.1.png',
    type: 'usado',
    description: 'Sedán 3 puertas, color blanco perlado, único dueño, impecable estado.',
  },
  {
    id: 4,
    make: 'Mercedes-Benz',
    model: 'A200 Urban',
    year: 2017,
    price: 27500,
    kms: 42747,
    fuel: 'Nafta',
    transmission: 'Automática',
    image: '/images/used-cars/a200.1.png',
    type: 'usado',
    description: 'Sedán 5 puertas, caja automática, único dueño, impecable, color gris claro.',
    priceCurrency: 'USD',
  },
  {
    id: 5,
    make: 'Citroën',
    model: 'C3',
    year: 2021,
    price: 18500000,
    kms: 38000,
    fuel: 'Nafta',
    transmission: 'Manual',
    image: '/images/used-cars/c3.1.png',
    type: 'usado',
    description: 'Hatchback compacto con diseño moderno y eficiencia de combustible.',
  },
  {
    id: 6,
    make: 'Renault',
    model: 'Clio',
    year: 2020,
    price: 16500000,
    kms: 42000,
    fuel: 'Nafta',
    transmission: 'Manual',
    image: '/images/used-cars/clio1.png',
    type: 'usado',
    description: 'Hatchback urbano con excelente relación precio-calidad.',
  },
  {
    id: 7,
    make: 'Fiat',
    model: 'Cronos',
    year: 2022,
    price: 19500000,
    kms: 35000,
    fuel: 'Nafta',
    transmission: 'Manual',
    image: '/images/used-cars/cronos1.png',
    type: 'usado',
    description: 'Sedán compacto con diseño italiano y tecnología moderna.',
  },
  {
    id: 8,
    make: 'Renault',
    model: 'Kangoo Express 1.6 Confort',
    year: 2015,
    price: 13500000,
    kms: 146900,
    fuel: 'Nafta/GNC',
    transmission: 'Manual',
    image: '/images/used-cars/kangoo1.png',
    type: 'usado',
    description: 'Nafta/GNC 5° generación, 1 portón lateral, 2 asientos, con 2 tubos, color azul.',
  },
  {
    id: 9,
    make: 'Kia',
    model: 'Sportage EX 2.0 A/T 4X4 CRDI',
    year: 2019,
    price: 45900000,
    kms: 30000,
    fuel: 'Diesel',
    transmission: 'Automática',
    image: '/images/used-cars/kia1.png',
    type: 'usado',
    description: 'Todo terreno diesel, impecable, nuevo, único dueño sin detalles, color gris.',
  },
  {
    id: 10,
    make: 'Renault',
    model: 'Laguna',
    year: 2019,
    price: 23500000,
    kms: 65000,
    fuel: 'Nafta',
    transmission: 'Automática',
    image: '/images/used-cars/laguna1.png',
    type: 'usado',
    description: 'Sedán mediano con confort y tecnología francesa.',
  },
  {
    id: 11,
    make: 'Suzuki',
    model: 'Maruti Gypsy GLS',
    year: 1994,
    price: 19900000,
    kms: 89000,
    fuel: 'Nafta',
    transmission: 'Manual',
    image: '/images/used-cars/maruti1.png',
    type: 'usado',
    description: 'Motor 1.0L 4X4, canvas top, caja manual, único en el país, digno de ver, todo 0 km, impecable 100%, color rojo.',
  },
  {
    id: 12,
    make: 'Audi',
    model: 'Q5 2.0 TFSI 211CV S-Tronic Quattro',
    year: 2013,
    price: 25900000,
    kms: 130000,
    fuel: 'Nafta',
    transmission: 'Automática',
    image: '/images/used-cars/q5.1.png',
    type: 'usado',
    description: 'Único dueño, 130.000 kmts, exterior blanco, color gris plata.',
  },
  {
    id: 13,
    make: 'Volkswagen',
    model: 'Up!',
    year: 2021,
    price: 12500000,
    kms: 28000,
    fuel: 'Nafta',
    transmission: 'Manual',
    image: '/images/used-cars/up1.png',
    type: 'usado',
    description: 'Hatchback urbano ultra compacto con diseño alemán.',
  },
  {
    id: 14,
    make: 'Volkswagen',
    model: 'Vento GLI 2.0TSI 230cv DQ',
    year: 2019,
    price: 38900000,
    kms: 51000,
    fuel: 'Nafta',
    transmission: 'Automática',
    image: '/images/used-cars/ventogli1.png',
    type: 'usado',
    description: 'Impecable, contado o financiado, exterior gris oscuro.',
  },
  {
    id: 15,
    make: 'BMW',
    model: '530D Executive 3.0L',
    year: 2024,
    price: 18500000,
    kms: 0,
    fuel: 'Diesel',
    transmission: 'Automática Steptronic 6ª',
    image: '/images/used-cars/Bmw530D/a4b657_194ae5adf64c4d1a9b755fc192b64037mv2.png',
    type: 'usado',
    description: 'Caja Steptronic Automática 6ª Secuencial, 4 Puertas Diesel',
  },
  {
    id: 16,
    make: 'Mercedes Benz',
    model: '380 SEC Coupe',
    year: 1990,
    price: 24900,
    kms: 95808,
    fuel: 'Nafta',
    transmission: 'Automática',
    image: '/images/used-cars/MB-380SEC/a4b657_5261d850c20e4fb6b021bdb81494f029mv2.png',
    type: 'usado',
    description: 'Único dueño! En impecable estado. Auto de colección.',
    priceCurrency: 'USD',
  },
  {
    id: 17,
    make: 'Mercedes Benz',
    model: 'Sportcoupe C230 V6 Evolution',
    year: 2006,
    price: 16900,
    kms: 0,
    fuel: 'Nafta',
    transmission: 'Automática',
    image: '/images/used-cars/MB-C230/a4b657_00020d7485a947d69ae72abb72603bdamv2.png',
    type: 'usado',
    description: 'Impecable estado. V6 Evolution Automático 2006.',
    priceCurrency: 'USD',
  },
];
