
import type { Vehicle } from './types';

export const VEHICLES_0KM: Vehicle[] = [
  {
    id: 1,
    make: 'Renault',
    model: 'Kwid Outsider 1.0',
    year: 2025,
    price: 18500000,
    kms: 0,
    fuel: 'Nafta',
    transmission: 'Manual',
    image: '/images/0km/mini-1743707561761.KWID-OUTSIDER-01.jpg',
    type: '0km',
    description: 'SUV compacta con diseño aventurero y tecnología moderna.',
  },
  {
    id: 2,
    make: 'Renault',
    model: 'Kwid Iconic 1.0',
    year: 2025,
    price: 17500000,
    kms: 0,
    fuel: 'Nafta',
    transmission: 'Manual',
    image: '/images/0km/mini-1743771826003.KWID-ICONIC-01.jpg',
    type: '0km',
    description: 'Versión icónica con equipamiento completo y confort premium.',
  },
  {
    id: 3,
    make: 'Fiat',
    model: 'Cronos 1.3',
    year: 2025,
    price: 22500000,
    kms: 0,
    fuel: 'Nafta',
    transmission: 'Manual',
    image: '/images/0km/mini-1747337165053.nuevo-fiat-cronos-15.jpg',
    type: '0km',
    description: 'Sedán compacto familiar con motor 1.3L 8 válvulas de 99 CV y 127 Nm. Fabricado en Argentina, incluye nueva parrilla Pixel, luces LED DRL, multimedia de 7" con Apple CarPlay y Android Auto inalámbrico, y 4 airbags.',
  },
  {
    id: 4,
    make: 'Renault',
    model: 'Stepway 1.6',
    year: 2025,
    price: 28500000,
    kms: 0,
    fuel: 'Nafta',
    transmission: 'Manual',
    image: '/images/0km/mini-1624984882569.1.jpg',
    type: '0km',
    description: 'Crossover urbano con motor HR16 1.6L, 115 CV, altura al suelo 185mm y baúl de 320 litros. Incluye cuatro airbags, control crucero, faros LED C-Shape y llantas de aleación 16".',
  },
  {
    id: 5,
    make: 'Renault',
    model: 'Logan Life 1.6',
    year: 2025,
    price: 24500000,
    kms: 0,
    fuel: 'Nafta',
    transmission: 'Manual',
    image: '/images/0km/mini-1667835477981.1.jpg',
    type: '0km',
    description: 'Sedán familiar con motor H4M 1.6L de 115 CV y 156 Nm. Versión básica con comando satelital, cierre centralizado, sistema de audio básico y equipamiento de seguridad reglamentario.',
  },
  {
    id: 6,
    make: 'Renault',
    model: 'Logan Intens 1.6',
    year: 2025,
    price: 27500000,
    kms: 0,
    fuel: 'Nafta',
    transmission: 'Manual',
    image: '/images/0km/mini-1673013426019.1.jpg',
    type: '0km',
    description: 'Sedán familiar con motor H4M 1.6L de 115 CV. Versión superior con Media Evolution® 7", Android Auto y Apple CarPlay, cámara de reversa, sensores de estacionamiento, ESP, HSA, faros DRL LED y mayor confort.',
  },
  {
    id: 7,
    make: 'Volkswagen',
    model: 'Polo Track',
    year: 2025,
    price: 27500000,
    kms: 0,
    fuel: 'Nafta',
    transmission: 'Manual',
    image: '/images/0km/mini-1691441178832.1.jpg',
    type: '0km',
    description: 'Hatchback compacto con motor 3 cilindros, torque de 170Nm, velocidad máxima 183km/h y aceleración 0-100 en 11.5s. Incluye ESC, ABS, 4 airbags, App Connect inalámbrico, cargador inalámbrico y sistema VW Play con Android Auto y Apple CarPlay.',
  },
  {
    id: 8,
    make: 'Renault',
    model: 'Sandero',
    year: 2025,
    price: 19500000,
    kms: 0,
    fuel: 'Nafta',
    transmission: 'Manual',
    image: '/images/0km/mini-1694204505047.1.jpg',
    type: '0km',
    description: 'Hatchback urbano con motor 1.6L 16 válvulas, baúl de 320 litros y capacidad para 5 pasajeros. Incluye cámara de estacionamiento trasera, control crucero, sistema Media Evolution® con pantalla de 7" y llantas de aleación 15".',
  },
  {
    id: 9,
    make: 'Fiat',
    model: 'Fiorino 1.3',
    year: 2025,
    price: 18500000,
    kms: 0,
    fuel: 'Nafta',
    transmission: 'Manual',
    image: '/images/0km/mini-1709563961450.1.jpg',
    type: '0km',
    description: 'Furgón utilitario pequeño con motor Firefly 1.3L de 99 CV y 130 Nm. Capacidad de carga 3.3m³ y 650kg. Incluye aire acondicionado, cierre centralizado, doble airbag, ABS, ESP, sensores de estacionamiento y alarma.',
  },
];

export const VEHICLES_USED: Vehicle[] = [
  {
    id: 7,
    make: 'BMW',
    model: '530D Executive 3.0L',
    year: 2024,
    price: 18500000,
    kms: 0,
    fuel: 'Diesel',
    transmission: 'Automática Steptronic 6ª',
    image: '/images/used-cars/bmw530d-main.png',
    type: 'usado',
    description: 'Caja Steptronic Automática 6ª Secuencial, 4 Puertas Diesel',
  },
  {
    id: 8,
    make: 'Mercedes Benz',
    model: '380 SEC Coupe',
    year: 1990,
    price: 24900, // USD
    kms: 95808,
    fuel: 'Nafta',
    transmission: 'Automática',
    image: '/images/used-cars/mb380sec-main.png',
    type: 'usado',
    description: 'Único dueño! En imejorable estado. Auto de colección.',
    priceCurrency: 'USD',
  },
  {
    id: 9,
    make: 'Mercedes Benz',
    model: 'Sportcoupe C230 V6 Evolution',
    year: 2006,
    price: 16900, // USD
    kms: 0,
    fuel: 'Nafta',
    transmission: 'Automática',
    image: '/images/used-cars/mbc230-main.png',
    type: 'usado',
    description: 'Impecable estado. V6 Evolution Automático 2006.',
    priceCurrency: 'USD',
  },
];
